### ISSUE TITLE
Yum returns a 403 when connecting to a repo with an x509 certguard content guard

### ISSUE THREAD

**Issue by paralllax** [pulp/pulp-certguard#168]
**Version**

These were installed via ansible via roles from the [squeezer](https://github.com/pulp/squeezer) ansible collection.

```
# pulp status | jq '.versions | .[1], .[4]'
{
  "component": "rpm",
  "version": "3.17.4"
}
{
  "component": "certguard",
  "version": "1.5.2"
}
```

**Describe the bug**

When setting signed certificates for yum to use to authenticate to a repo with an x509 certguard content guard yum still returns a 403.

**To Reproduce**

Presumably

1. Setup an x509 content guard with the root CA that is auto generated for pulp.

```
  - name: Create a simple content guard
    uri:
      url: "{{ certguard_x509_uri }}"
      user: admin
      password: "{{ pulp_secrets.pulp_pass }}"
      force_basic_auth: yes
      method: POST
      body_format: json
      status_code: 201
      body:
        name: "{{ certguard_guard_name }}"
        #-# slurp stores as base64 encoded string
        ca_certificate: "{{ slurped_ca_cert.content | b64decode }}"
```

2. Assign the content guard to an rpm distribution

```
    - name: Assign our content guard to the distribution
      uri:
        url: "https://{{ ansible_nodename }}{{ dist_info.distribution.pulp_href }}"
        user: admin
        password: "{{ pulp_secrets.pulp_pass }}"
        force_basic_auth: yes
        method: PATCH
        body_format: json
        status_code: 202
        body:
          content_guard: "https://{{ ansible_nodename }}{{ content_guard_href }}"
```

3. Generate and sign a client certificate and key with the CA mentioned above. Haven't created an ansible task for this yet.

```
# generate the key and csr
openssl req -config openssl.cnf -newkey rsa:2048 -sha256 -nodes -out my_pulp_cert.csr -outform PEM

# generate and sign the cert
openssl ca -config openssl.cnf -out my_pulp_cert.pem -infiles my_pulp_cert.csr
```

5. Set the ssl directives for the repo in the `.repo` file

```
sslclientcert = /etc/pulp/my_pulp_cert.pem
sslclientkey = /etc/pulp/pulp_privkey.pem
sslcacert = /etc/pulp/ca/root.crt
```

6. Run yum

**Expected behavior**

Yum should be able to authenticate with the signed ssl certificate/return a 200 status code.

**Additional context**

This is my repo file:

```
# cat /etc/yum.repos.d/test.repo
[tset-application]
name=test-application
enabled=1
sslverify=1
baseurl=https://pulptest.com/pulp/content/test-application-x86_64/
gpgcheck=0
repo_gpgcheck=0
sslclientcert = /etc/pulp/my_pulp_cert.pem
sslclientkey = /etc/pulp/pulp_privkey.pem
sslcacert = /etc/pulp/ca/root.crt
```

I pulled the settings from the notes here: https://github.com/pulp/pulp-certguard/issues/142

I verified the certificate does appear to work.

```
# cert=$(openssl x509 -inform PEM -in my_pulp_cert.pem); curl -I -H "X-CLIENT-CERT: $(urlencode ${cert})" 'https://pulptest.com/pulp/content/test-application-x86_64/'
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Thu, 07 Apr 2022 00:17:36 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 407
Connection: keep-alive
X-PULP-CACHE: HIT
```

Yum also does correctly pull them in:

```
# strace -f yum makecache --disablerepo=* --enablerepo=test-application 2>&1 | grep -Eo 'open.*(crt|\.pem)' | sort -u
open("/etc/pulp/ca/root.crt
open("/etc/pulp/my_pulp_cert.pem
open("/etc/pulp/pulp_privkey.pem
```

However it oddly still results in a 403: `[Errno 14] HTTPS Error 403 - Forbidden`. Usually a 403 would indicate the `X-CLIENT-CERT` header isn't being properly sent, but I am uncertain how to verify if this is the case. 

I saw this script, I am uncertain if it needs to be added/edited for the headers to work, or if the ssl directives in the repo file would suffice. 
- https://github.com/pulp/pulp-certguard/blob/main/contrib/yum/certguard.py
